spring:
  profiles:
    active: "dev"
  datasource:
    url: jdbc:postgresql://localhost:5432/danuma-lk
    username: postgres
    password: MyNewPass
    driver-classname: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
        hibernate:
            format_sql:true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
