name: Build and deploy Danuma-lk

on:
  push:
    branches:
      - master
  

jobs:
  build-deploy:
    name: Build and deploy Danuma-lk
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: danuma-lk
          POSTGRES_PASSWORD: MyNewPass
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
        
    - name: Unit Tests
      run: mvn -B test --file pom.xml

    - name: Build the application
      run: |
        mvn clean
        mvn -B package --file pom.xml

   
